# Dockerfile for onnx2tflite
FROM tensorflow/tensorflow:2.8.0

ARG USERNAME=hanyong

ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y zsh wget sudo git libusb-1.0-0-dev \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

ENV PATH="${PATH}:/home/${USERNAME}/.local/bin"

# RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

# 설치로 생성된 캐시 파일들을 삭제해서 용량 줄이기!
RUN apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/cache/* && \
    rm -rf /var/lib/log/*

RUN pip install --upgrade pip
RUN pip install gpustat \
    onnx-tf \
    protobuf==3.20.2 \
    tensorflow_probability==0.15.0 \
    tflite_support

USER $USERNAME

CMD ["zsh"]